export { default as getParcelsByQuery } from "./getParcelsByQuery.js";
export { default as getParcelById } from "./getParcelById.js";
export { default as createParcel } from "./createParcel.js";
export { default as deleteParcel } from "./deleteParcel.js";
export { default as getMyParcels } from "./getMyParcels.js";
export { default as updateParcel } from "./updateParcel.js";
export { default as updateDriver } from "./updateDriver.js";
export { default as updateTracking } from "./updateTracking.js";
export { default as updatePayment } from "./updatePayment.js";
